const { EntitySchema } = require('typeorm');

module.exports = new EntitySchema({
  name: 'Invoice',
  tableName: 'invoices',
  columns: {
    id: { primary: true, type: 'int', generated: true },
    removed: { type: 'boolean', default: false },
    createdBy: { type: 'int' },
    number: { type: 'int' },
    year: { type: 'int' },
    content: { type: 'text', nullable: true },
    recurring: { type: 'varchar', nullable: true },
    date: { type: 'date' },
    expiredDate: { type: 'date' },
    client: { type: 'int' },
    converted: { type: 'simple-json', nullable: true },
    items: { type: 'simple-json', nullable: true },
    taxRate: { type: 'float', default: 0 },
    subTotal: { type: 'float', default: 0 },
    taxTotal: { type: 'float', default: 0 },
    total: { type: 'float', default: 0 },
    currency: { type: 'varchar', default: 'NA' },
    credit: { type: 'float', default: 0 },
    discount: { type: 'float', default: 0 },
    payment: { type: 'simple-json', nullable: true },
    paymentStatus: {
      type: 'enum',
      enum: ['PAID', 'UNPAID', 'PARTIAL', 'OVERDUE'],
      default: 'UNPAID',
    },
    isOverdue: { type: 'boolean', default: false },
    approved: { type: 'boolean', default: false },
    notes: { type: 'text', nullable: true },
    status: { type: 'varchar', default: 'draft' },
    pdf: { type: 'varchar', nullable: true },
    files: { type: 'simple-json', nullable: true },
    updated: { type: 'timestamp', updateDate: true, default: () => 'CURRENT_TIMESTAMP' },
    created: { type: 'timestamp', createDate: true, default: () => 'CURRENT_TIMESTAMP' },
  },
});
