const { EntitySchema } = require('typeorm');

module.exports = new EntitySchema({
  name: 'Quote',
  tableName: 'quotes',
  columns: {
    id: { primary: true, type: 'int', generated: true },
    removed: { type: 'boolean', default: false },
    createdBy: { type: 'int' },
    converted: { type: 'boolean', default: false },
    number: { type: 'int' },
    year: { type: 'int' },
    content: { type: 'text', nullable: true },
    date: { type: 'date' },
    dueDate: { type: 'date' },
    client: { type: 'int' },
    items: { type: 'simple-json', nullable: true },
    taxRate: { type: 'float', default: 0 },
    subTotal: { type: 'float', default: 0 },
    taxTotal: { type: 'float', default: 0 },
    total: { type: 'float', default: 0 },
    credit: { type: 'float', default: 0 },
    currency: { type: 'varchar', default: 'NA' },
    discount: { type: 'float', default: 0 },
    notes: { type: 'text', nullable: true },
    status: {
      type: 'enum',
      enum: ['DRAFT', 'SENT', 'CONVERTED'],
      default: 'DRAFT',
    },
    approved: { type: 'boolean', default: false },
    isExpired: { type: 'boolean', default: false },
    pdf: { type: 'varchar', nullable: true },
    files: { type: 'simple-json', nullable: true },
    updated: { type: 'timestamp', updateDate: true, default: () => 'CURRENT_TIMESTAMP' },
    created: { type: 'timestamp', createDate: true, default: () => 'CURRENT_TIMESTAMP' },
  },
});
